### ISSUE TITLE
FreeDOS-B Build Automation System

### ISSUE THREAD

**Issue by eersoy93** [bilgisayarcilik/FreeDOS-B#2]
I suggest you should a build automation system for FreeDOS B. The system (for live CD) may has those steps:

- Downloading packages / Compiling and packaging components with patches (if necessary)

- Adding other files will include on CD to output directory

- Making ISO includes the output directory content

**Comment by ercanersoy** [comment]
Automation system for Linux has been added.

**Comment by ercanersoy** [comment]
Automation system for Microsoft Windows and Mac OS X has been added.
